# Generated by Django 5.2 on 2026-06-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="complexity",
            field=models.IntegerField(null=True, verbose_name="Сложность"),
        ),
        migrations.AlterField(
            model_name="task",
            name="T_or_F",
            field=models.BooleanField(default=False, verbose_name="Выполнена или нет"),
        ),
    ]
