# Generated by Django 5.2 on 2026-05-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="fire_mode_bool",
            field=models.DateField(null=True),
        ),
    ]
